title: (Knowledge) Graphs and (Knowledge) Networks
logo: assets/images/kg-kn-logo.png
description: A (proposed) REU site at Wright State University
show_downloads: false

remote_theme: pages-themes/minimal@v0.2.0
plugins:
    - jekyll-remote-theme
